future: true
permalink: /:title/
url: https://paintersg.github.io
name: SJX
author: SGAFPZ
qq: 1104611441
email: shaojx5@mail2.sysu.edu.cn

duoshuo: paintersg
beian: 
cnzz: 
weibo: 
github: paintersg
about: "这里是 paintersg 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
